/**
 * Render the one social card this site has: `public/og-default.png`.
 *
 *   node scripts/og-default.mjs
 *
 * ### Why there is a script and not a renderer
 *
 * This repo deliberately has no per-page OG renderer (`tds.notes.noOgRenderer`
 * in package.json): a product's picture comes from a partner, and the Amazon
 * PA-API forbids rehosting or editing it. So a product page uses
 * `product.imageUrl` and everything else falls back to this file.
 *
 * ### Why it exists at all
 *
 * It did not. `Layout.astro` has pointed `og:image` at `/og-default.png` since
 * the site was built and the file was never there, so every page without its
 * own picture — the front page, every category page, every product whose
 * partner sent no image — advertised a 404 as its preview. A 404 image looks
 * exactly like a site that never declared one.
 *
 * Own artwork only: the brand mark, the brand colours, the site's own words.
 * Nothing here is a partner's asset, which is the whole reason this is a fixed
 * card rather than a template with a product photo in it.
 *
 * The output is COMMITTED. One static file, regenerated by hand when the brand
 * changes — a build step for a single unchanging image would cost every build
 * and gain nothing.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import sharp from "sharp";

const OUT = resolve(process.cwd(), "public/og-default.png");
const MARK = resolve(process.cwd(), "public/brand/td-logomark.webp");

/** Brand values, matching `tds-shared`'s navy/paper/bordeaux tokens. */
const NAVY = "#141b30";
const PAPER = "#f7f6f2";
const BORDEAUX = "#7a2740";
const MUTED = "#a8a69f";

const WIDTH = 1200;
const HEIGHT = 630;

const escape = (value) =>
  value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

// "TDShop" and the German tagline — the same words `i18n.ts` uses, kept here
// as literals on purpose: a card is regenerated by hand, and reaching into the
// site's runtime copy from a one-off script would couple them for no gain.
const NAME = "TDShop";
const TAGLINE = "Technik und Digitalisierung, kuratiert.";
const DETAIL = "Mit eigener Einschätzung statt Herstellertext.";

const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${WIDTH}" height="${HEIGHT}" viewBox="0 0 ${WIDTH} ${HEIGHT}">
  <rect width="${WIDTH}" height="${HEIGHT}" fill="${NAVY}"/>
  <!-- The brand bar, the same device the site puts under its headings. -->
  <rect x="96" y="212" width="132" height="10" fill="${BORDEAUX}"/>
  <text x="96" y="340" font-family="Georgia, 'Times New Roman', serif" font-size="104" font-weight="700" fill="${PAPER}">${escape(NAME)}</text>
  <text x="96" y="412" font-family="Helvetica, Arial, sans-serif" font-size="40" fill="${PAPER}">${escape(TAGLINE)}</text>
  <text x="96" y="470" font-family="Helvetica, Arial, sans-serif" font-size="30" fill="${MUTED}">${escape(DETAIL)}</text>
  <text x="96" y="566" font-family="Helvetica, Arial, sans-serif" font-size="26" fill="${MUTED}">shop.tracht-digital.de</text>
  <!-- A paper tile under the mark. The logomark is navy, and navy on navy is
       the mark being technically present and practically invisible — the same
       trap the site's own dark surfaces have. Tinting the mark instead would
       alter the brand asset; giving it a ground does not. -->
  <rect x="${WIDTH - 316}" y="${(HEIGHT - 284) / 2}" width="284" height="284" rx="28" fill="${PAPER}"/>
</svg>`;

const mark = await sharp(readFileSync(MARK)).resize({ width: 220 }).png().toBuffer();
const markMeta = await sharp(mark).metadata();

const png = await sharp(Buffer.from(svg))
  .composite([{ input: mark, left: WIDTH - 316 + 32, top: Math.round((HEIGHT - markMeta.height) / 2) }])
  .png({ compressionLevel: 9 })
  .toBuffer();

writeFileSync(OUT, png);
const { width, height } = await sharp(png).metadata();
console.log(`og-default.png — ${width}x${height}, ${(png.length / 1024).toFixed(1)} KB`);
